enable-magisk-update = true
logging-to-file = true
parallel-jobs = 1

[YouTube-Rina]
enabled = true
build-mode = "both"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Rina"
module-prop-name = "youtube-rina"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = """\
    --options-file assets/rina/patches.json --options-update \
    """

[Music-Rina]
enabled = false
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Rina"
module-prop-name = "music-rina"
arch = "arm64-v8a" # rip compatibility 
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = """\
    --options-file assets/rina-music/patches.json --options-update \
    """

[YouTube-Miku]
enabled = true
build-mode = "both"
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Miku"
module-prop-name = "youtube-miku"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = """\
    --options-file assets/miku/patches.json --options-update \
    """

[Music-Miku]
enabled = false
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Miku"
module-prop-name = "music-miku"
arch = "arm64-v8a" # rip compatibility 
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = """\
    --options-file assets/miku-music/patches.json --options-update \
    """
