enable-magisk-update = true
logging-to-file = true
parallel-jobs = 1

[Youtube-Rina]
enabled = true
build-mode = "both"
module-prop-name = "youtube-rina"
exclusive-patches = true
excluded-patches = ""
included-patches = """\
    'Custom branding' 'Seekbar' 'Remove background playback restrictions' \
    'Video ads' 'Hide ads' 'Video Quality' 'Theme' 'Change form factor' \
    'Return Youtube Dislike' 'Miniplayer' 'SponsorBlock' \
    """
patcher-args = """\
    -e 'Change header' -Ocustom=./assets/rina/header/ \
    -e 'Custom branding' -OcustomName='RinaTube' -OcustomIcon=./assets/rina/icon/ \
    -e 'Theme' -OdarkThemeBackgroundColor='#FF290025' -OlightThemeBackgroundColor='#FFFCCFF3' \
    """
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Rina-Extended]
enabled = true
app-name = "Youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RinaEX"
build-mode = "both"
module-prop-name = "youtube-rina-ex"
included-patches = "'Custom header for YouTube'"
patcher-args = "--legacy-options assets/rina/patches.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube-Miku-Extended]
enabled = true
app-name = "Youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "MikuEX"
build-mode = "both"
module-prop-name = "youtube-miku-ex"
included-patches = "'Custom header for YouTube'"
patcher-args = "--legacy-options assets/miku/patches.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
